// main42.cc is a part of the PYTHIA event generator.
// Copyright (C) 2019 Torbjorn Sjostrand.
// PYTHIA is licenced under the GNU GPL v2 or later, see COPYING for details.
// Please respect the MCnet Guidelines, see GUIDELINES for details.

// Authors: Mikhail Kirsanov <Mikhail.Kirsanov@cern.ch>.

// Keywords: basic usage; command file; command line option; hepmc; LHE file;

// This program illustrates how a file with HepMC events
// can be generated by Pythia8.
// Input and output files are specified on the command line, e.g. like
// ./main42.exe main42.cmnd hepmcout42.dat > out
// The main program contains no analysis; this is intended to happen later.
// It therefore "never" has to be recompiled to handle different tasks.

// WARNING: typically one needs 25 MB/100 events at the LHC.
// Therefore large event samples may be impractical.

#include "stdio.h"
#include "stdlib.h"
#include "time.h"
#include "string"

#include "Pythia8/Pythia.h"
#include "Pythia8Plugins/HepMC2.h"
#include "Pythia8/StandardModel.h"

using namespace Pythia8;

int main(int argc, char* argv[]) {

  // Check that correct number of command-line arguments
  if (argc != 3) {
    cerr << " Unexpected number of command-line arguments. \n You are"
         << " expected to provide one input and one output file name. \n"
         << " Program stopped! " << endl;
    return 1;
  }

  // Check that the provided input name corresponds to an existing file.
  ifstream is(argv[1]);
  if (!is) {
    cerr << " Command-line file " << argv[1] << " was not found. \n"
         << " Program stopped! " << endl;
    return 1;
  }

  // Confirm that external files will be used for input and output.
  cout << "\n >>> PYTHIA settings will be read from file " << argv[1]
       << " <<< \n >>> HepMC events will be written to file "
       << argv[2] << " <<< \n" << endl;

  // Interface for conversion from Pythia8::Event to HepMC event.
  HepMC::Pythia8ToHepMC ToHepMC;

  // Specify file where HepMC events will be stored.
  HepMC::IO_GenEvent ascii_io(argv[2], std::ios::out);

  // Generator.
  Pythia pythia;

  // Read in commands from external file.
  pythia.readFile(argv[1]);

  srand (time(NULL));
  pythia.readString(("Random:setSeed = on"));
  pythia.readString(("Random:seed = " + std::to_string(rand() % 10000000)).c_str());

  // Extract settings to be used in the main program.
  int    nEvent    = pythia.mode("Main:numberOfEvents");
  int    nAbort    = pythia.mode("Main:timesAllowErrors");

  std::string decay_switch = "0";
  pythia.readString(("111:mayDecay = " + decay_switch).c_str()); //pi0
  pythia.readString(("211:mayDecay = " + decay_switch).c_str()); //pi+
  pythia.readString(("221:mayDecay = " + decay_switch).c_str()); //eta
  pythia.readString(("321:mayDecay = " + decay_switch).c_str()); //K+ 
  pythia.readString(("310:mayDecay = " + decay_switch).c_str()); //Kshort
  pythia.readString(("130:mayDecay = " + decay_switch).c_str()); //Klong 
  pythia.readString(("3122:mayDecay = " + decay_switch).c_str());//Lambda0
  pythia.readString(("3212:mayDecay = " + decay_switch).c_str());//Sigma0 
  pythia.readString(("3112:mayDecay = " + decay_switch).c_str());//Sigma- 
  pythia.readString(("3222:mayDecay = " + decay_switch).c_str());//Sigma+ 
  pythia.readString(("3312:mayDecay = " + decay_switch).c_str());//Xi-    
  pythia.readString(("3322:mayDecay = " + decay_switch).c_str());//Xi0    
  pythia.readString(("3334:mayDecay = " + decay_switch).c_str());//Omega-    

  // Initialization.
  pythia.init();

  AlphaStrong alphastrong;
  alphastrong.init();
  double lambda = alphastrong.Lambda6();
  cout << lambda << endl;

  // Begin event loop.
  int iAbort = 0;
  for (int iEvent = 0; iEvent < nEvent; ++iEvent) {

    // Generate event.
    if (!pythia.next()) {

      // If failure because reached end of file then exit event loop.
      if (pythia.info.atEndOfFile()) {
        cout << " Aborted since reached end of Les Houches Event File\n";
        break;
      }

      // First few failures write off as "acceptable" errors, then quit.
      if (++iAbort < nAbort) continue;
      cout << " Event generation aborted prematurely, owing to error!\n";
      break;
    }

    // Construct new empty HepMC event and fill it.
    // Units will be as chosen for HepMC build, but can be changed
    // by arguments, e.g. GenEvt( HepMC::Units::GEV, HepMC::Units::MM)
    HepMC::GenEvent* hepmcevt = new HepMC::GenEvent();
    ToHepMC.fill_next_event( pythia, hepmcevt );

    // Write the HepMC event to file. Done with it.
    ascii_io << hepmcevt;
    delete hepmcevt;

  // End of event loop. Statistics.
  }
  pythia.stat();

  // Done.
  return 0;
}
